export = {
  IP: "IP",
  ROLE: "role",
  ROLE_NAME: "role name",
  PRODUCT: "product",
  PHONE_NUMBER: "phone number",
  EMAIL: "email",
  CATEGORY: "category",
  TAG: "tag",
  USERNAME: "username",
  USERNAME_OR_EMAIL: "username or email",
  DESCRIPTION: "description",
  PERMISSION: "permission",
  USER: "user",
  USERS: "users",
  PHONENUMBER: "phone number",
  PROFILE: "profile",
  BIRTH_DATE: "birth date",
  GENDER: "gender",
  PASSWORD: "password",
  NEW_PASSWORD: "news password",
  COUPON_CODE: "coupon code",
  CODE: "code",
  PARENT_CATEGORY: "parent category",
  META_KEYWORD: "meta keyword",
  META_TITLE: "meta title",
  DISCOUNT: "discount",
  NAME: "name",
  DATE: "date",
  COST: "cost",
  AMOUNT: "amount",
  ACTIVE_TOKEN: "active token",
  NUMBER: "number",
  VALUE: "value",
  DATA: "data",
  CATEGORY_ID: "category ID",
  CURRENCY: "currency",
  COMMENT: "comment",
  USER_TYPE: "user type",
  CERTIFICATE: "certificate",
  COUNTRY: "country",
  STATUS: "status",
};
