import mongoose from "mongoose";
import argonService from "../../app/security/argon.service";
import userTypes from "../../app/enums/userTypes.enum";
//Password = admin
let hashedPassword =
  "$argon2i$v=19$m=4096,t=50,p=1$1XbH1O3IoPWheBthw/D1Ig$+7dOOEEMeJUJWtUc0hCo1GEiGWpEToXXGKIt4Y1c4tz0+/frIG+gjKKVOM73+qujayE";

export = [
  {
    _id: new mongoose.Types.ObjectId("5f72d4a912007e8a468f2b10"),
    type: userTypes.client,
    email: "sinasadigh1@gmail.com",
    emailVerified: true,
    phoneNumber: "09141234567",
    phoneVerified: true,
    username: "client1",
    password: hashedPassword,
    protected: false,
    isActive: true,
  },
  {
    _id: new mongoose.Types.ObjectId("5f72d57a8b3062935a4b589e"),
    type: userTypes.client,
    email: "sinasadigh2@gmail.com",
    emailVerified: true,
    phoneNumber: "09141234568",
    phoneVerified: true,
    username: "client2",
    password: hashedPassword,
    protected: false,
    isActive: true,
  },
  {
    _id: new mongoose.Types.ObjectId("5f72d5803df74e80e60b7b37"),
    type: userTypes.client,
    email: "sinasadigh3@gmail.com",
    emailVerified: true,
    phoneNumber: "09141234564",
    phoneVerified: true,
    username: "client3",
    password: hashedPassword,
    protected: false,
    isActive: true,
  },
  {
    _id: new mongoose.Types.ObjectId("5f72d5803df74e80e60b7b38"),
    type: userTypes.client,
    email: "sinasadigh4@gmail.com",
    emailVerified: true,
    phoneNumber: "091412345655",
    phoneVerified: true,
    username: "client4",
    password: hashedPassword,
    protected: false,
    isActive: true,
  },
  {
    _id: new mongoose.Types.ObjectId("5f72d5803df74e80e60b7b39"),
    type: userTypes.client,
    email: "sinasadigh5@gmail.com",
    emailVerified: true,
    phoneNumber: "09141234556",
    phoneVerified: true,
    username: "client5",
    password: hashedPassword,
    protected: false,
    isActive: true,
  },
  {
    _id: new mongoose.Types.ObjectId("5f72d5803df74e80e60b7b40"),
    type: userTypes.client,
    email: "sinasadigh6@gmail.com",
    emailVerified: true,
    phoneNumber: "09141234557",
    phoneVerified: true,
    username: "client6",
    password: hashedPassword,
    protected: false,
    isActive: true,
  },
  {
    _id: new mongoose.Types.ObjectId("5f72d5803df74e80e60b7b41"),
    type: userTypes.client,
    email: "sinasadigh7@gmail.com",
    emailVerified: true,
    phoneNumber: "09141234558",
    phoneVerified: true,
    username: "client7",
    password: hashedPassword,
    protected: false,
    isActive: true,
  },
  {
    _id: new mongoose.Types.ObjectId("5f72d5803df74e80e60b7b42"),
    type: userTypes.client,
    email: "sinasadigh8@gmail.com",
    emailVerified: true,
    phoneNumber: "09141234553",
    phoneVerified: true,
    username: "client8",
    password: hashedPassword,
    protected: false,
    isActive: true,
  },
  {
    _id: new mongoose.Types.ObjectId("5f72d5803df74e80e60b7b43"),
    type: userTypes.client,
    email: "sinasadigh9@gmail.com",
    emailVerified: true,
    phoneNumber: "09141234552",
    phoneVerified: true,
    username: "client9",
    password: hashedPassword,
    protected: false,
    isActive: true,
  },
  {
    _id: new mongoose.Types.ObjectId("5f72d5803df74e80e60b7b44"),
    type: userTypes.client,
    email: "sinasadigh10@gmail.com",
    emailVerified: true,
    phoneNumber: "09141234551",
    phoneVerified: true,
    username: "client10",
    password: hashedPassword,
    protected: false,
    isActive: true,
  },
];
